### ISSUE TITLE
Search on crm_multifield types

### ISSUE THREAD

**Issue by uni4online** [HappyRoot/bitrix24-connector#1]
When creating a query to get a list then when adding a filter on a crm_multifield  (i.e. EMAIL or PHONE) then the filter is not applied and the full list is returned.

`
Bitrix24Query query = Bitrix24QueryBuilder
        .Create()
        //.AddFilter("UF_CRM_1614593442", idNumber) //ID Number
        .AddFilter("PHONE", phonenumber) //Phone number
        .Build();

Bitrix24Response<IEnumerable<Bitrix24Contact>> contacts = await bitrix24Connector.Contacts.ListAsync(query);
`

**Comment by HappyRoot** [comment]
Try using .**AddFilter** ("PHONE", phone number, **Bitrix24Comparer.None**). This is a feature of Bitrix24 for all crm_multifield. The next build will have Bitrix24Comparer.None by default.
