### ISSUE TITLE
Example of how to pass auth to the API Client

### ISSUE THREAD

**Issue by sashok2k** [HappyRoot/bitrix24-connector#2]
Hi

Library looks promising, but it lacks proper explanation of how to pass access_token to cleint.

Could you provide example of how to do that?

**Comment by HappyRoot** [comment]
At the moment, the library only supports operation through a webhook.

**Comment by sashok2k** [comment]
am i right to assume that library receives auth token from webhook?

**Comment by HappyRoot** [comment]
> Могу ли я предположить, что библиотека получает токен аутентификации от веб-перехватчика?

For rest api Bitrix24, you can use Inbound webhooks. In this case, no additional authorization is required.

Creating an Inbound Webhook
https://training.bitrix24.com/support/training/course/?COURSE_ID=169&LESSON_ID=20176&LESSON_PATH=13643.20142.20176

Are you from Russia?
Создание Входящего вебхука
https://dev.1c-bitrix.ru/learning/course/?COURSE_ID=99&LESSON_ID=8581

**Comment by sashok2k** [comment]
Спасибо) посмотрю, не являюсь разработчиком битрикс

**Comment by HappyRoot** [comment]
> Спасибо) посмотрю, не являюсь разработчиком битрикс24

Суть в том что создается так называемый "входящий webhook", он не требуется авторизации, ему необходимо задать права на доступ к ресурсам, все обращения к rest api можно выполнять через него без дополнительной авторизации.
У данного способа есть некоторые ограничения, ознакомится можно в документации:

https://dev.1c-bitrix.ru/learning/course/?COURSE_ID=99&LESSON_ID=8581
